### ISSUE TITLE
error: failed to run custom build command for `openssl v0.9.24`

### ISSUE THREAD

**Issue by danconte72** [imazen/imageflow#224]
I've tried to build and got this problem
```bash
$ /.build.sh test
...
error: failed to run custom build command for `openssl v0.9.24`
process didn't exit successfully: `/home/meumobi/PROJECTS/imageflow/target/debug/build/openssl-7d464e70a21ffa53/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::begin_panic
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panicking.rs:408
   6: build_script_build::main
             at ./build.rs:16
   7: std::rt::lang_start::{{closure}}
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/rt.rs:64
   8: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
   9: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  10: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  11: std::rt::lang_start
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/rt.rs:64
  12: main
  13: __libc_start_main
  14: _start
```

### Env
```bash
root@vps673381:/home/meumobi/PROJECTS/imageflow# cargo -V
cargo 1.36.0-beta (c4fcfb725 2019-05-15)
root@vps673381:/home/meumobi/PROJECTS/imageflow# rustc -V
rustc 1.36.0-beta.1 (3a5d62bd5 2019-05-22)
root@vps673381:/home/meumobi/PROJECTS/imageflow# openssl version
OpenSSL 1.1.0j  20 Nov 2018 (Library: OpenSSL 1.1.1b  26 Feb 2019)
root@vps673381:/home/meumobi/PROJECTS/imageflow# 
```

Can u help find out why is happening?

**Comment by vdias38** [comment]
I've tried to upgrade deps using openssl:0.9.24 (identified by `$ cargo tree -p openssl:0.9.24 -i`)

I've upgraded on imageglow_server/Cargo.tml
- reqwest 0.6 to 0.9
- hyper-native-tls 0.2 to 0.3

I've upgraded on imageglow_helpers/Cargo.tml
- hyper-openssl v0.2.7 to v0.3.0
- openssl 0.9 to 0.10
- reqwest 0.6 to 0.9

It solved some compiling errors BUT reach following error on build:

```
   Compiling imageflow_helpers v0.1.0 (/home/meumobi/PROJECTS/imageflow/imageflow_helpers)
error[E0432]: unresolved import `hyper_openssl::OpensslClient`
  --> imageflow_helpers/src/fetching.rs:13:5
```

OpensslClient has been removed on [hyper_openssl v0.3.0](https://github.com/sfackler/hyper-openssl/compare/v0.2.7...v0.3.0) **should apply changes on `imageflow_helpers/src/fetching.rs`** in order to compile on Debian 9 w/ OpenSSL 1.1.1

**Comment by lilith** [comment]
Thank you! I will work on this.

**Comment by lilith** [comment]
This should be fixed in master. Can you confirm it now builds on your machine?

**Comment by danconte72** [comment]
I've got the new code and build successfully.
Thanks for the fix.
